/**
 * Represents raw scraped content from a source like Reddit.
 */
export interface ScrapedContent {
  id: string;
  source: string;
  title: string;
  body: string;
  url: string;
  score: number;
  commentCount: number;
  subreddit?: string | null;
  scrapedAt: string;
  usedAt?: string | null;
}

/**
 * Represents an individual scene in a generated script.
 */
export interface Scene {
  text: string;
  visualDescription?: string;
  durationInSeconds?: number;
}

/**
 * Represents a complete script generated by AI.
 */
export interface GeneratedScript {
  title: string;
  description: string;
  tags: string[];
  scenes: Scene[];
}

/**
 * Represents a video project as stored in the database.
 */
export interface VideoProject {
  id: string;
  contentId: string;
  scriptJson: string; // JSON string representation of GeneratedScript
  audioPath?: string | null;
  videoPath?: string | null;
  thumbnailPath?: string | null;
  status: 'draft' | 'review' | 'approved' | 'uploaded';
  youtubeId?: string | null;
  title: string;
  description: string;
  tags: string; // JSON string representation of string[]
  createdAt: string;
  publishedAt?: string | null;
}
